language: generic

os:
  - linux
  - osx

osx_image: xcode9
dist: trusty

install:
  - git clone --depth 1 https://github.com/thinca/vim-themis && (cd vim-themis && git show HEAD)
  - |
    if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      brew update
      HOMEBREW_NO_AUTO_UPDATE=1 brew install macvim python3
      pip3 install codecov covimerage --user
    else
      pip install codecov covimerage --user
    fi

before_script:
  - uname -a
  - vim --version
  - covimerage --version

script:
  - cd test/ && PROFILE_LOG=profile.txt ../vim-themis/bin/themis .

after_success:
  - covimerage write_coverage profile.txt
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)

cache: pip
