language: generic
# `language: python` is not available:
#   https://travis-ci.community/t/python-3-6-3-7-and-3-8-binaries-cant-be-downloaded-on-arm/5641

matrix:
  include:
    - os: linux
      env: TARGET=vim
    - os: linux
      env: TARGET=nvim
    - os: osx
      env: TARGET=vim
    - os: osx
      env: TARGET=nvim

dist: xenial

# Avoid the default old macOS 10.13
osx_image: xcode11.3

# Speed up `brew install` on macOS worker
env:
  global:
    - HOMEBREW_NO_INSTALL_CLEANUP=1

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      # This is necessary because python@2 prevents python@3 installation
      # Homebrew addon is not available because unlinking python@2 is necessary before `brew install` :(
      brew unlink python@2 || true
      brew install macvim python
    fi
  - git clone --depth 1 --single-branch https://github.com/thinca/vim-themis && (cd vim-themis && git rev-parse HEAD)
  - |
    if [[ "$TARGET" == 'nvim' ]]; then
      if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
        curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-macos.tar.gz
        tar xzf nvim-macos.tar.gz
      else
        curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
        tar xzf nvim-linux64.tar.gz
      fi
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      pip3 install codecov covimerage
    else
      pip3 install codecov covimerage --user
    fi
  - export PATH=$(pwd)/nvim-${TRAVIS_OS_NAME}64/bin:$PATH

before_script:
  - uname -a
  - $TARGET --version
  - covimerage --version
  - python3 --version

script:
  - cd test/ && THEMIS_VIM=$TARGET PROFILE_LOG=profile.txt ../vim-themis/bin/themis .

after_success:
  - covimerage write_coverage profile.txt
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)

cache: pip

addons:
  apt:
    packages:
      - python3
      - python3-pip
  homebrew:
    update: true
